# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile
# Author: Trevor Roberts Jr (VMTrooper@gmail.com)

Vagrant.configure("2") do |config|
  config.vm.box = "precise64_nocm"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box"
end
