# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :controller do |controller|
    controller.vm.box = "hashicorp/precise64"
  end
  config.vm.define :compute do |compute|
    compute.vm.box = "hashicorp/precise64"
    compute.vm.hostname = "compute"
  end
end