# -*- mode: ruby -*-
# vi: set ft=ruby :
# vagrant up --provider=vmware_fusion

# Vagrantfile
# Author: Trevor Roberts Jr (VMTrooper@gmail.com)

Vagrant.configure("2") do |config|
  config.vm.define :controller do |controller|
    controller.vm.box = "precise64_nocm"
    controller.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box"
    controller.vm.hostname = "controller.puppet.local"
  end

  config.vm.define :compute do |compute|
    compute.vm.box = "precise64_nocm"
    compute.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box"
    compute.vm.hostname = "compute.puppet.local"
  end
end
