# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile
# Author: Trevor Roberts Jr (VMTrooper@gmail.com)
nodelist = {
'controller' => 200,
'compute' => 210,
}

Vagrant.configure("2") do |config|
  config.vm.box = "precise64_nocm"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box"

  nodelist.each do |prefix, fourth_octet|
    config.vm.define "#{prefix}" do |box|
      box.vm.hostname = "#{prefix}.puppet.local"
      box.vm.network :private_network, ip: "192.168.10.#{ip_start+i}", :netmask => "255.255.255.0"
      box.vm.network :public_network
      #box.vm.provision :shell, :path => "#{prefix}.sh"
      #box.vm.provision :puppet
    end
  end
end
